### ISSUE TITLE
ERROR  lazer 27200 gameplay updateLeaderboard Couldn't read long at 19f4e5ae

### ISSUE THREAD

**Issue by 0120-500-500** [tosuapp/tosu#266]
1. Describe your issue as detailed as possible
I keep getting an error when I start the game.
This was also happening when I was using Stable
No particular inconvenience has occurred, but just in case.

2. Where does **tosu.exe** located (Folder path, Example: D:\tosu\tosu.exe)
"E:\tosu\tosu.exe"

3. Record video showing:
   - tosu.env & config.ini
   - Enable debug in settings
   - Close tosu, then start it again
   - Open osu and show what not working
4. Windows or Linux
Windows

![image](https://github.com/user-attachments/assets/dc4e2ccf-b586-4277-b5eb-f276f5721e3b)

https://github.com/user-attachments/assets/2dc41d3f-2dfe-444c-820d-9412272a6026

**Comment by cyperdark** [comment]
@KotRikD

**Comment by KotRikD** [comment]
All lazer memory stuff please address to @xxCherry

**Comment by unqxl** [comment]
Also getting this type of error on Lazer.
lazer 2648 gameplay updateLeaderboard Couldn't read long at 1a053af5

**Comment by KotRikD** [comment]
Regular memory issues, that any memory reader can't handle properly. There are no concrete steps to reproduce the problem. All I can advise is to ignore these errors when they occur in small numbers. If they start spamming, then open the issue (again, you need steps to reproduce the issue, otherwise it will be a useless ish that I will also close right away :)).
